### ISSUE TITLE
为何会有 Jare 这个分支？

### ISSUE THREAD

**Issue by jwu** [exdev/ex2d-dev#1]
目前我们的分支应该都是在master上，还没有进行发布。当进入发布状态后，我们会开 stable 分支来进行稳定版本的发布。

为何会出现 Jare  分支？如果不是为了特定功能不希望进入master 也就是我们的开发分支，提交应该都进入到master分支，这样才能够保证开发人员每次都是在最新版本上提交自己的代码。如果没必要，请将 Jare 分支去掉。

**Comment by jareguo** [comment]
这个分支用来同步一些在不同的机器上的未做完的功能

**Comment by jwu** [comment]
好的。
