### ISSUE TITLE
Sprite Font 在 Scene Editor 和 Game View 中的渲染 Depth 不一样。

### ISSUE THREAD

**Issue by jwu** [exdev/ex2d-dev#11]
RT， 当有两份在同一layer的 sprite font 进行渲染的时候，他们的渲染次序在 Scene Editor 和 Game View 中表现不一致

**Comment by jareguo** [comment]
无法重现，是否是因为你测试时使用了Debug的Inspector视图，导致depth_未能更新？

**Comment by jwu** [comment]
我测试的时候实在同一份 layer 里加入了两份不同的 bitmap-font

**Comment by jwu** [comment]
测试发现，不在同一张atlas 的两份 sprite 在同一个 layer 中，会发生这种问题。 无论 depth 如何调整，即使相同 depth也会有排序问题。
