### ISSUE TITLE
ex2D的所有资源编辑器在激活时需要能够自动辨认已选中的资源文件

### ISSUE THREAD

**Issue by nantas** [exdev/ex2d-dev#16]
该问题在Sprite Animation Editor，Atlas Editor里都会出现。

重现方法：
- 拿Sprite Animation来说，首先确认Sprite Animation Editor没有处在激活状态（比如和其他view共用一个窗口，而且当前激活的tab不是Sprite Animation Editor）
- 在Project View里选中一个sprite animation clip
- 激活Sprite Animation Editor（或从菜单重新打开一个）
- 这时Editor里显示空的，用户必须在Project View里先选中任何一个其他文件，然后再重新选择刚才的clip，才会在editor里显示。

这个问题从1.X时代就有，最好可以解决一下~

**Comment by jwu** [comment]
该问题已经解决，commit 里写错了， Fix Issue #18 是解决这个问题。
