### ISSUE TITLE
通过Project View窗口上方的Create按钮无法创建资源到当前目录

### ISSUE THREAD

**Issue by nantas** [exdev/ex2d-dev#17]
_注意：这个问题只会在Project View使用Two Column Layout时出现_
- 首先在Project View里选中一个目录
- 点击窗口左上角的Create，选择ex2D/Sprite Animation Clip
- 这时会发现资源被创建到了Assets目录下

如果使用One Column Layout时，这个问题就不会出现。

**Comment by jwu** [comment]
这是一个 Unity3D 的 Bug。我们只能通过 Selection.activeObject 来取得当前 Project Window 中选择的 object，并通过它反推出 selected-path。当点击 Create 的时候，Selection.activeObject 会变成 null。

Unity3D 自己是通过一个叫做 AssetDatabase.GetUniquePathNameAtSelectedPath 的函数来获取当前路径，但是这个函数他并没有开放给用户，我需要向 Unity 提交这个Bug。

目前版本中，我引入类似 2D Toolkit 的做法，就是当 Selection,activeObject 取不到路径的时候，默认弹出一个 Save 的对话框，让你选择你要保存的地方。

目前版本中，还是推荐采用右键点击保存的方法来制作。
