### ISSUE TITLE
Atlas改名后重新Build，TextureInfo不会移动到新的目录下

### ISSUE THREAD

**Issue by nantas** [exdev/ex2d-dev#18]
重现步骤：
- 建立一个新的Atlas，放入一些贴图，然后Apply，Build
- 将Atlas改名，然后重新Apply，Build
- 这时Project View的当前目录下会出现以新Atlas命名的目录，里面有最后build出来的Atlas贴图。但以原来Atlas命名的目录依然存在，而且所有TextureInfo还在原目录。

如果重命名后build会创建新目录来存放Atlas贴图的话，那么TextureInfo也应该被自动搬运过来。

当然这个问题不影响用户手动移动TextureInfo，但如果改名之后误删了原来的目录，那么Atlas里的贴图就会丢失了。

**Comment by jwu** [comment]
是这样的，Build 和 Sync 是两个操作。当 atlas 改名后，要做的是 sync 操作。我需要检查看看 Build 中是否可以做 sync 的检查。
