### ISSUE TITLE
Atlas Editor内贴图大小不足时欠缺提示

### ISSUE THREAD

**Issue by jareguo** [exdev/ex2d-dev#19]
当大小不足时log打印Failed to layout atlas element，发生atlas重叠现象。
建议1 将log改为弹出提示
建议2 默认使用MaxRect

**Comment by jwu** [comment]
建议1， 弹出log已经修改。

建议2， 默认创建的 atlas 本来就是 MaxRect, 这里是什么意思呢？

**Comment by jareguo** [comment]
二. 看错了，可能是我以前创建的atlas，所以不是mex rect
