### ISSUE TITLE
往Scene Editor里拖放Sprite, 按Play按钮后，Game View中不会出现Sprite.

### ISSUE THREAD

**Issue by jwu** [exdev/ex2d-dev#2]
往Scene Editor里拖放Sprite, 按Play按钮后，Game View中不会出现Sprite。
此时，如果停止Play，然后继续往该Layer里拖放Sprite，会发现又会新创建一个_exMesh GameObject。而原先的 _exMesh GameObject 里的 Mesh 为空。

**Comment by jareguo** [comment]
bug已修复，不过Game View的Camera还要进一步瞄准才能看到。

**Comment by jwu** [comment]
我觉得 GameView 里的 OnPreRender 激活只在 isPlaying 状态下有效，其余时候，应该是由 SceneEditor 去触发 Mesh 的更新操作。我会将这些改动做进之后的版本中。
