### ISSUE TITLE
Atlas layout算法中对大尺寸的贴图padding失败

### ISSUE THREAD

**Issue by nantas** [exdev/ex2d-dev#22]
Atlas Editor如果包括和atlas width宽度相同的texture，使用默认layout算法时会不允许加padding

**Comment by jwu** [comment]
这个 Issue  在 MaxRect 下并没有想象中那么好解决。

我一开始的做法是采用

``` csharp
System.Math.Min(processElements[i].width + _padding, _atlasWidth); 
System.Math.Min(processElements[i].height + _padding, _atlasHeight ); 
```

但是这样一来，就限制了 width, height 大小必须和 atlas width/height 一样，而无法在算法中运用旋转匹配。还需要更进一步思考。

**Comment by jwu** [comment]
后来我换了一种思路，将 Atlas Rect 扩充成 _atlasWidth + _padding, _atlasHeight + _padding 的大小来容纳贴图，就可以正确存放。
