### ISSUE TITLE
运行时当只有Scene View处于激活状态时，无法实时更新渲染

### ISSUE THREAD

**Issue by nantas** [exdev/ex2d-dev#23]
如果三大游戏窗口Game View，Scene View，2D Scene Editor中只有Scene View可见，那么运行游戏时Scene View中无法看到实时渲染更新。

**Comment by jareguo** [comment]
刚才说错了，这个问题是由于MainCamera没有进行渲染，所以就没能激活它所在的ex2DRenderer的OnPreRender导致的。

**Comment by jareguo** [comment]
将ex2DRenderer.OnPreRender里面的代码放到LateUpdate里面执行了。用户如果不是导入包，而是直接复制脚本的话，需要手工修改优先级，确保ex2DRenderer最后执行。
