### ISSUE TITLE
Layer.Add()应该可以对GameObject操作，exLayer组件需要加上更新子物体

### ISSUE THREAD

**Issue by nantas** [exdev/ex2d-dev#24]
Layer.Add目前只能接受exSpriteBase参数，但实际使用中用户可能需要将GameObject也纳入Layer管理。

在这个前提下，需要在exLayer Component上加入Update功能，点击后根据目前场景里该layer物体下的子物体来更新处在该Layer上的物体列表。

**Comment by jareguo** [comment]
用户可以将任意东西放到layer下，但是如果不是sprite，在layer下不会有任何效果。所以更新物件列表没有用处吧？
另外将sprite放到layer下的话，它会自动加到layer里。反之亦然。

**Comment by jareguo** [comment]
已在dev分支加上
exLayer.Add(GameObject) 
exLayer.Remove(GameObject)
