### ISSUE TITLE
exSpriteAnimation使用Event时报错

### ISSUE THREAD

**Issue by nantas** [exdev/ex2d-dev#27]
NullReferenceException: Object reference not set to an instance of an object
exSpriteAnimation.Step (Single _deltaTime) (at Assets/ex2D/Runtime/Components/exSpriteAnimation.cs:660)
exSpriteAnimation.LateUpdate () (at Assets/ex2D/Runtime/Components/exSpriteAnimation.cs:358)

**Comment by jareguo** [comment]
应该是event触发时修改了动画引起的，已修复，可再测试几次
