### ISSUE TITLE
运行时添加的sprite在停止后会出现Can't destroy Transform component... 的错误

### ISSUE THREAD

**Issue by jwu** [exdev/ex2d-dev#3]
要添加多个才会出现：
Can't destroy Transform component. If you want to destroy the game object please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.

**Comment by jareguo** [comment]
[ex2D] 将 exMesh 标记成 DontSave 并放置在 root 下。通过 exLayer 的 ExecuteInEditMode 控制他的销毁与重建。
https://tower.im/projects/b5f3950329234d5d8577ff8f26a0d1d6/todos/b16ddf8c79c54b529e8620b0b34d0f15/
改了这个之后，没出现这个问题了。
