### ISSUE TITLE
向exLayer里添加的Sprite在退出程序并重新运行后依然存在

### ISSUE THREAD

**Issue by xw0** [exdev/ex2d-dev#37]
1. 运行程序
2. 动态创建包含exSprite的GameObject并用layer.Add()添加到layer里
3. 退出运行
4. 此时在hierachy中看到对应的layer下没有GameObject，但在Scene view里还是可以看到刚才添加的objects
5. 重新运行程序。上次运行时添加的GameObject重新出现在hierarchy view的layer物体下

这个貌似是个新bug。v2.0.1_2013_09_19 (beta3)里应该没有这个问题

**Comment by jareguo** [comment]
我这边使用beta3及beta4版本进行测试，均未能复现，麻烦你用beta4再测看看...

**Comment by xw0** [comment]
update到beta4。这个问题消失了。应该是某个中间版本问题。
