### ISSUE TITLE
当Atlas含有diced数据时，再添加内容进atlas时会报错

### ISSUE THREAD

**Issue by nantas** [exdev/ex2d-dev#40]
You should GenerateDiceData first
UnityEngine.Debug:LogError(Object)
exTextureInfo:BeginDiceData() (at Assets/ex2D/Runtime/Assets/exTextureInfo.cs:427)
exAtlasEditor:LayoutAtlasElements(Boolean) (at Assets/ex2D/Editor/exAtlasEditor.cs:1135)
exAtlasEditor:OnGUI() (at Assets/ex2D/Editor/exAtlasEditor.cs:195)
UnityEditor.DockArea:OnGUI()

NullReferenceException: Object reference not set to an instance of an object
exTextureInfo.GetDiceData (Int32 _diceIndex) (at Assets/ex2D/Runtime/Assets/exTextureInfo.cs:444)
exAtlasUtility.GetElementList (.exAtlas _atlas) (at Assets/ex2D/Editor/Utilities/exAtlasUtility.cs:234)
exAtlasEditor.LayoutAtlasElements (Boolean _forced) (at Assets/ex2D/Editor/exAtlasEditor.cs:1140)
exAtlasEditor.OnGUI () (at Assets/ex2D/Editor/exAtlasEditor.cs:195)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Applications/buildAgent/work/c514da0c8183631c/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

**Comment by nantas** [comment]
@tinytail 
另外使用diced sprite时会导致部分sprite在game view中不可见，只能在2DScene Editor里看到
还会导致一些depth排序的错乱

**Comment by jareguo** [comment]
似乎还是有点问题，回去再查查。

**Comment by nantas** [comment]
![dicedatlasbug](https://f.cloud.github.com/assets/344547/1434031/f596189e-410a-11e3-8d36-05e0fa7ceb57.jpeg)

还是有问题，diced空白区域会被加到atlas里。

**Comment by nantas** [comment]
现在报错是不会了，但是diced sprite的空白区域还是会存在在atlas里，见我上面贴得图。
