### ISSUE TITLE
大量物体放进Layer时会产生额外的layer GO和draw call

### ISSUE THREAD

**Issue by nantas** [exdev/ex2d-dev#42]
可以在sheeptap2的LevelSel场景中看到
场景中所有sprite都属于同一个atlas，但产生了过多layer物体和drawcall

![layerbug](https://f.cloud.github.com/assets/344547/1433959/d8bf2160-4106-11e3-90ff-5d94f021259e.jpeg)

**Comment by jareguo** [comment]
layer目前对同depth的sprite使用的是ordered排序，当添加不同atlas的sprite进去时，会按照添加顺序先后渲染。这就会导致必须将不同atlas的sprite逐个拆分成多个mesh。

**Comment by nantas** [comment]
这个场景里所有物体都是同一个atlas

2013/10/30 Jare notifications@github.com

> layer目前对同depth的sprite使用的是ordered排序，当添加不同atlas的sprite进去时，会按照添加顺序先后渲染。这就会导致必须将不同atlas的sprite逐个拆分成多个mesh。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/exdev/ex2d_dev/issues/42#issuecomment-27360305
> .

## 

aBit Games Indie game dev blog - aBitGames.com
aBit Games Facebook -
aBitGameshttp://www.facebook.com/pages/ABit-Games/174285692598974
My Twitter - @nantas  http://twitter.com/nantas
Weibo - @南塔斯 http://weibo.com/nantas

**Comment by jareguo** [comment]
大量是指多大？

**Comment by nantas** [comment]
@tinytail 你得一个sheeptap2的dev分支试试就行啦

**Comment by jareguo** [comment]
使用最新数羊分支没看到这个问题，之前可能用了多个材质

**Comment by nantas** [comment]
ok，重新检查之后确认之前使用字体时有atlas不一致的情况，现在应该只是combine上限导致的分层
