### ISSUE TITLE
启动游戏会改变 Unity3D 本身界面。（只有非 pro 版本会重现）

### ISSUE THREAD

**Issue by jwu** [exdev/ex2d-dev#44]

**Comment by jwu** [comment]
经过验证发现，这是 Unity 的一个bug。当使用 Unity 非 Pro 版本时。只要在场景里加入随便脚本。然后添加 OnGUI 函数就会触发这个Bug。

如

``` csharp
using UnityEngine;
using System.Collections;

public class Test : MonoBehaviour {

    // Use this for initialization
    void Start () {

    }

    // Update is called once per frame
    void Update () {

    }

    void OnGUI () {
    }
}
```

然后反复运行该场景即可重现。

@tinytail @nantas

**Comment by jwu** [comment]
正确的UI显示：
![screen shot 2013-10-31 at 10 42 46](https://f.cloud.github.com/assets/174891/1446633/c8c1894e-423a-11e3-9a80-b3262becb77d.png)

错误的UI显示:
![screen shot 2013-10-31 at 10 42 26](https://f.cloud.github.com/assets/174891/1446635/ce44fa2c-423a-11e3-8ffa-a8d413fcd0c9.png)

**Comment by jareguo** [comment]
这个情况Pro版也经常会

**Comment by jwu** [comment]
4.3 版本已经解决了这个问题
