### ISSUE TITLE
在iPhone4上跑数羊2.0时，出现vertex buffer推送问题

### ISSUE THREAD

**Issue by nantas** [exdev/ex2d-dev#47]
更新的机型在处理大量vertex推送没有问题，但在iphone4上会莫名其妙出现绵羊消失的情况。

另外当pool里的绵羊数量超过100只（都处于未激活状态）时，帧数会下降一半

![img_1083](https://f.cloud.github.com/assets/344547/1458769/bb964a56-4394-11e3-8805-5e9da39bf63b.PNG)

**Comment by jwu** [comment]
补充一点，有时候还会出现闪烁。

**Comment by jareguo** [comment]
可否尝试在程序启动前动态修改 exLayer.maxDynamicMeshVertex 的值，用于控制每个mesh的最大顶点数量。
这个值目前是static的，只要修改一次即可，修改成600试试？
这个值越大，drawcall越少，但之前是90000，可能过大了。
