### ISSUE TITLE
在数羊Level Sel 场景中出现某个Layer 在 Scene 里显示，但是 Game View 里无法正确显示。

### ISSUE THREAD

**Issue by jwu** [exdev/ex2d-dev#49]
重现方法：
1. 得 sheeptap2 项目 27d6980b0a610a64ff19a9d4473ea134b9af6957 以后的版本。
2. 打开 LevelSel 场景运行。
3. 点击 Play 按钮。

这个时候会 transition 到 store panel, 但是会发现 store panel 没有显示。

在 Scene View (2D, 3D 都可) 中看到的情况：
![screen shot 2013-11-04 at 2 47 09 pm](https://f.cloud.github.com/assets/174891/1463084/f7ec15ba-451c-11e3-8795-08a09eb5a4d2.png)

在 Game View 中看到的情况:

![screen shot 2013-11-04 at 2 47 13 pm](https://f.cloud.github.com/assets/174891/1463089/20567d10-451d-11e3-9152-cb8f5a5475d0.png)

**Comment by jareguo** [comment]
如果是开启2D Scene Editor导致的不正常，已经在ex2D的d7370d解决
