### ISSUE TITLE
在SpriteFont里输入字体里没有的字符时，报错

### ISSUE THREAD

**Issue by nantas** [exdev/ex2d-dev#54]
报错之后即使修正字符也会一直持续出错，必须退出
在出现没有的字符时应该出warning警示，然后不进行相关字符的渲染

NullReferenceException: Object reference not set to an instance of an object
exFont.GetCharInfo (Char _symbol, UnityEngine.CharacterInfo& _charInfo) (at Assets/ex2D/Runtime/Assets/exFont.cs:262)
ex2D.Detail.SpriteFontBuilder.BuildLine (ex2D.Detail.SpriteFontParams& sfp, .exList`1 _vertices, .exList`1 _uvs, System.Int32& _charIndex, System.Int32& _vbIndex, Vector2 _texelSize, Single _top) (at Assets/ex2D/Runtime/Components/exSpriteFont.cs:1096)
ex2D.Detail.SpriteFontBuilder.BuildTextInLocalSpace (.exSpriteBase _sprite, ex2D.Detail.SpriteFontParams& sfp, .exList`1 _vertices, Int32 _vbIndex, .exList`1 _uvs) (at Assets/ex2D/Runtime/Components/exSpriteFont.cs:1032)
ex2D.Detail.SpriteFontBuilder.BuildText (.exSpriteBase _sprite, ex2D.Detail.SpriteFontParams& sfp, Space _space, .exList`1 _vertices, Int32 _vbIndex, .exList`1 _uvs) (at Assets/ex2D/Runtime/Components/exSpriteFont.cs:911)
exSpriteFont.GetVertices (Space _space) (at Assets/ex2D/Runtime/Components/exSpriteFont.cs:455)
exLayeredSprite.GetWorldVertices () (at Assets/ex2D/Runtime/Components/Internal/exLayeredSprite.cs:243)
exPlane.GetWorldAABoundingRect () (at Assets/ex2D/Runtime/Components/Internal/exPlane.cs:102)
exSceneEditor.MapBoundingRect (Rect _rect, .exLayeredSprite _node) (at Assets/ex2D/Editor/exSceneEditor.cs:1373)
exSceneEditor.DoCulling (Rect _rect) (at Assets/ex2D/Editor/exSceneEditor.cs:1406)
exSceneEditor.SceneViewField (Rect _rect) (at Assets/ex2D/Editor/exSceneEditor.cs:591)
exSceneEditor.Layout_SceneViewField (Int32 _width, Int32 _height) (at Assets/ex2D/Editor/exSceneEditor.cs:575)
exSceneEditor.OnGUI () (at Assets/ex2D/Editor/exSceneEditor.cs:186)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Applications/buildAgent/work/c514da0c8183631c/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

**Comment by jareguo** [comment]
我这边报错的地方不太一样，不过已修复。
