### ISSUE TITLE
向Atlas Editor中多次拖入Texture时，容易丢失已有的TextureInfo。

### ISSUE THREAD

**Issue by jareguo** [exdev/ex2d-dev#7]

**Comment by jwu** [comment]
这个问题是因为拖入的Texture居然名字相同。。。。。。。。所以我需要对同名不同guid的texture报警告

**Comment by jareguo** [comment]
如果名字相同，能否使用相对路径做后缀？路径中的斜杠用@替换。例如 sheep1@level1@superSeep.asset

**Comment by jwu** [comment]
目前，加入“同名，不同texture” 到atlas中，会报警告并弹出yes or no 窗口让用户选择。

**Comment by jwu** [comment]
不了，因为你很难知道用户采用什么样的路径名。如用户可能写  double_sheep/ip3/xxxx, fever_sheep/ip3/xxxx ，那么前缀都是 ip3 一样无法成功。王楠觉得用户自己约束命名规则即可。
