### ISSUE TITLE
atlas editor的sync窗口bug

### ISSUE THREAD

**Issue by jareguo** [exdev/ex2d-dev#9]
点击atlas editor的sync按钮，在弹出覆盖texture info对话框时，点击屏幕的其它区域，这时对话框消失，只留下进度条，造成Unity死锁。

**Comment by jwu** [comment]
暂时无解

**Comment by jareguo** [comment]
对话框去掉其实更好。今后如果有同类功能，建议使用和scene editor中删除layer时一样的对话框
